### ISSUE TITLE
Where is the sparsefusion folder mentioned at environment.md?

### ISSUE THREAD

**Issue by sungmin9939** [zhizdev/mvdfusion#2]
Hi

Thanks for the great work

I just wonder where can i find sparsefusion folder mentioned at [https://github.com/zhizdev/mvdfusion/blob/main/ENVIRONMENT.md#install-other-mvd-fusion-requirements](url)

**Comment by zhizdev** [comment]
Hey! It's a typo from the older environment set up from sparsefusion. Please ignore that. Thanks!
