### ISSUE TITLE
The list of filtered set

### ISSUE THREAD

**Issue by LiyingCV** [zhizdev/mvdfusion#5]
Greets! Could you share the list of filtered set?

**Comment by zhizdev** [comment]
Here are two lists: 

Positive top 100k [link](https://drive.google.com/file/d/1xi9rcB8UeHEVUG2kYzgg341FZo8dqIaz/view?usp=sharing).

Positive top 400k [link](https://drive.google.com/file/d/1s9dX6BuLhErzgevJwal-6sdHk8lP6Is-/view?usp=sharing).

**Comment by LiyingCV** [comment]
> Here are two lists:
> 
> Positive top 100k [link](https://drive.google.com/file/d/1xi9rcB8UeHEVUG2kYzgg341FZo8dqIaz/view?usp=sharing).
> 
> Positive top 400k [link](https://drive.google.com/file/d/1s9dX6BuLhErzgevJwal-6sdHk8lP6Is-/view?usp=sharing).

Thanks!
