### ISSUE TITLE
the value of `feed_prev_depth` in `mvd_train.config`?

### ISSUE THREAD

**Issue by thucz** [zhizdev/mvdfusion#6]
I want to train MVD-Fusion on my customed dataset. Can you also provide the `mvd_train.config` file(including the value of `feed_prev_depth`)?

**Comment by zhizdev** [comment]
thanks for checking out or repo! 

feed_pred_depth is false during training and optional (default to false) during inference. training code and config are uploaded.

**Comment by thucz** [comment]
Thanks!
