### ISSUE TITLE
why `n_pts_per_ray=1` in `mvd_train.config`?

### ISSUE THREAD

**Issue by thucz** [zhizdev/mvdfusion#7]
In your paper, you said in Sec3.2, "we sample D = 3 depths...", but the actual value in `mvd_train.config` is 1: 
`n_pts_per_ray=1`.

**Comment by zhizdev** [comment]
Indeed, our released model is trained with `n_pts_per_ray=3`, updating mvd_train.config.

**Comment by thucz** [comment]
Thanks!
