### ISSUE TITLE
How can i get multi-view image

### ISSUE THREAD

**Issue by throb081** [zhizdev/mvdfusion#9]
您好，拜读读了您的论文后，对您的工作很感兴趣。但是想请教一下，代码里面有没有指令可以直接生成多视图图片呢，运行了您的指令 python demo.py -c configs/mvd_gso.yaml后，生成的是gift，有没有办法可以生成的是图片结果呢？

**Comment by elegant666yu** [comment]
我想请问您是如何实现多视图生成的，请问是修改了他的代码吗？ @throb081
